FROM openjdk:21-bookworm 

WORKDIR /app

COPY .mvn .mvn
COPY src src
COPY mvnw .
COPY pom.xml .

RUN ./mvnw package -Dmaven.test.skip=true

ENV REDIS_HOST=localhost 
ENV REDIS_PORT=6379
ENV REDIS_DATABASEUSER=0
ENV REDIS_DATABASEWORD=1
ENV REDIS_USERNAME=
ENV REDIS_PASSWORD=
ENV DICTIONARYAPI_KEY=abc123


EXPOSE ${PORT}

ENV PORT=8080

ENTRYPOINT SERVER_PORT=${PORT} java -jar target/miniproject-0.0.1-SNAPSHOT.jar